# ~/.tmux.conf
# vim:set ft=tmux:

# Options to make tmux more pleasant
set -g mouse on 
set -g default-terminal "tmux-256color"

# remaps
unbind C-b
set -g prefix C-_
bind C-_ send-prefix

# Split panes using | and -
bind | split-window -hc "#{pane_current_path}"
bind _ split-window -vc "#{pane_current_path}"
unbind '"'
unbind %

bind a new-window -c "#{pane_current_path}"

# easy config reload
bind r source ~/.tmux.conf; #display "Reloaded!" # (uncomment for debugging)

# bind pane movements
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# resizing
bind -r C-j resize-pane -D 15
bind -r C-k resize-pane -U 15
bind -r C-h resize-pane -L 15
bind -r C-l resize-pane -R 15

bind "'" switch-client -t'{marked}'

# Numbering
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Enable mouse control
set -g mouse on

# window swapping
bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

# toggle window
bind space last-window
bind [ previous-window
bind ] next-window

# # Window/title control
# # Prevent zsh, Oh My Zsh, Powerlevel10k, vim, ssh, etc. from renaming tmux windows.
# setw -g automatic-rename off
# setw -g allow-rename off

# # Do not let tmux set the outer terminal title either.
# set -g set-titles off
# set -g set-titles-string ""

# Manual rename bindings
bind , command-prompt -I "#W" "rename-window '%%'"
bind '$' command-prompt -I "#S" "rename-session '%%'"

# join window into pane
bind g choose-window 'join-pane -h -s "%%"'
bind G choose-window 'join-pane -s "%%"'

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""

# toggle session - this is down here because it breaks tree-sitter
bind \\ switch-client -l

# TPM plugin manager {{{
## List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @plugin 'catppuccin/tmux#v2.3.0'
# --- catppuccin config --- {{{

run '~/.config/tmux/plugins/tmux/catppuccin.tmux'

#### Configure the catppuccin plugin
set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_window_text " #W "
set -g @catppuccin_window_current_text " #W "
set -g status-left-length 100
set -g status-right-length 100
set -g status-left ""
set -g @catppuccin_window_flags "none" # none, icon, or text

set -g status-right "#{E:@catppuccin_status_session}"
# set -g status-right "#{E:@catppuccin_status_application}"
# set -ag status-right "#{E:@catppuccin_status_uptime}"
# set -agF status-right "#{E:@catppuccin_status_cpu}"
# set -agF status-right "#{E:@catppuccin_status_battery}"
# set -g @plugin 'tmux-plugins/tmux-battery'

# }}}

# }}}


## Initialize TMUX plugin manager (Always has to be at the end!!!!!!)
run '~/.tmux/plugins/tpm/tpm'

